const INTERNAL_SERVER_ERROR = 'INTERNAL SERVER ERROR';
const UNAUTHORIZED = 'UNAUTHORIZED';
const INCORRECT_URL = 'INCORRECT URL';
const BAD_REQUEST = 'BAD REQUEST';
const FORBIDDEN = 'FORBIDDEN';
const NOT_FOUND = 'NOT FOUND';
const CONFLICT = 'CONFLICT';
const EMAIL_EXISTS = 'Email already exist';

module.exports = {
  INTERNAL_SERVER_ERROR,
  UNAUTHORIZED,
  INCORRECT_URL,
  BAD_REQUEST,
  FORBIDDEN,
  NOT_FOUND,
  CONFLICT,
  EMAIL_EXISTS,
};
